[project]
name = "pit-predict"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.3"
dependencies = [
    "fastf1>=3.6.0",
    "ipykernel>=6.30.0",
    "numpy>=2.3.2",
    "pandas>=2.3.1",
    "torch>=2.7.1",
    "tqdm>=4.67.1",
]
